image: node:latest

variables:
    TRAVIS_OS_NAME: linux

stages:
  - production

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - mkdir ~/.ssh
    - printf "%s\n" "${GITHUB_JSSWARMSDK_DEPLOY_KEY}" > ~/.ssh/id_rsa
    - printf "Host github.com\n User git\n IdentityFile ~/.ssh/id_rsa\n Port 22" > ~/.ssh/config
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - dpl --provider=cloudfoundry --username=$CF_USERNAME --password=$CF_PASSWORD --organization="Swarm Fund" --api=api.run.pivotal.io --space=development
  only:
    - dev-vlad

mirror:
    stage: production
    script:
        - apt-get -qq update && apt-get -qq install git
        - git config --global push.default simple
        - git checkout ${CI_COMMIT_REF_NAME}
        - git merge
        - mkdir ~/.ssh
        - printf "%s\n" "${GITHUB_BARNSWALLOW_DEPLOY_KEY}" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        - echo "Pushing to git@github.com:${GITHUB_REPO}.git"
        - git push git@github.com:${GITHUB_BARNSWALLOW_REPO}.git
        - git push git@github.com:${GITHUB_BARNSWALLOW_REPO}.git --tags
